version: "3.1"

networks:
  infra:

volumes:
  mysql_data:
  redis_data:

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - infra
    ports:
      - 3306:3306
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
    networks:
      - infra
    ports:
      - 6379:6379
    restart: always

  order:
    container_name: order
    image: order:v1.0.2
    build:
      context: ..
      dockerfile: services/order/deploy/Dockerfile
    volumes:
      - /srv/configs/order:/app/configs
      - /srv/logs/order:/app/logs
    restart: always
    environment:
      - service_name=order
      - grpc_port=9090
      - http_port=10000
    networks:
      - infra
    ports:
      - 10000:10000
